idf_component_register(
    SRCS
        "audio_service.c"
    INCLUDE_DIRS "."
    REQUIRES
        nb_hal
        freertos
        log
        esp_common
        esp_timer
        sound_analysis_service
        synth_service
        wake_service
        audio_playback_service_v2
        audio_processor_service
        audio_io_service_v2
        voice_activity_service_v2
        voice_capture_session_v2
        infra
        espressif__esp-sr
)
