#!/usr/bin/env python3
"""Generate NoiseBot overlay icon masks from PBM P1 source files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "source"
OUTPUT = ROOT / "generated" / "nb_ui_overlay_icons.h"


@dataclass(frozen=True)
class Icon:
    name: str
    width: int
    height: int
    stride: int
    data: bytes


def _tokens(path: Path) -> list[str]:
    out: list[str] = []
    for line in path.read_text(encoding="ascii").splitlines():
        line = line.split("#", 1)[0]
        out.extend(line.split())
    return out


def read_pbm(path: Path) -> Icon:
    tokens = _tokens(path)
    if len(tokens) < 4 or tokens[0] != "P1":
        raise ValueError(f"{path}: expected PBM P1")

    width = int(tokens[1])
    height = int(tokens[2])
    pixels: list[str] = []
    for token in tokens[3:]:
        if all(ch in "01" for ch in token):
            pixels.extend(token)
        else:
            pixels.append(token)
    expected = width * height
    if len(pixels) != expected:
        raise ValueError(f"{path}: expected {expected} pixels, got {len(pixels)}")
    if any(p not in {"0", "1"} for p in pixels):
        raise ValueError(f"{path}: PBM pixels must be 0 or 1")

    stride = (width + 7) // 8
    packed = bytearray(stride * height)
    for y in range(height):
        for x in range(width):
            if pixels[(y * width) + x] == "1":
                packed[(y * stride) + (x // 8)] |= 0x80 >> (x % 8)

    name = path.stem.upper().replace("-", "_")
    return Icon(name=name, width=width, height=height, stride=stride, data=bytes(packed))


def _format_bytes(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def render_header(icons: list[Icon]) -> str:
    parts = [
        "/* Generated by icons/tools/generate_overlay_icons.py. Do not edit. */",
        "#ifndef NB_UI_OVERLAY_ICONS_H",
        "#define NB_UI_OVERLAY_ICONS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint8_t width;",
        "    uint8_t height;",
        "    uint8_t stride;",
        "    const uint8_t *mask;",
        "} nb_ui_overlay_icon_t;",
        "",
    ]

    for icon in icons:
        parts.extend(
            [
                f"static const uint8_t NB_UI_OVERLAY_ICON_{icon.name}_MASK[] = {{",
                _format_bytes(icon.data),
                "};",
                "",
                f"static const nb_ui_overlay_icon_t NB_UI_OVERLAY_ICON_{icon.name} = {{",
                f"    {icon.width}U,",
                f"    {icon.height}U,",
                f"    {icon.stride}U,",
                f"    NB_UI_OVERLAY_ICON_{icon.name}_MASK,",
                "};",
                "",
            ]
        )

    parts.extend(["#endif /* NB_UI_OVERLAY_ICONS_H */", ""])
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()

    icons = [read_pbm(path) for path in sorted(SOURCE_DIR.glob("*.pbm"))]
    if not icons:
        raise RuntimeError(f"no PBM icons found in {SOURCE_DIR}")

    rendered = render_header(icons)
    if args.check:
        current = OUTPUT.read_text(encoding="ascii") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT} is stale", file=sys.stderr)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
